
# Syntax highlighting
markdown:            redcarpet
highlighter:         pygments

# Permalinks
permalink:           /blog/:year/:month/:day/:title
relative_permalinks: true

# Setup
timezone:            Asia/Sydney # eg. Asia/Kathmandu
locale:              en_us # eg. en_us
name:				         Fabio Pereira
title:               'Fabio Pereira'
tagline:             'Go see, ask why, show respect'
description:         'A blog with ideas and thoughts on Agile, Digital Transformation and Behavioral Economics'
url:                 http://www.fabiopereira.me
rss:                 rss feed url
baseurl:             '/'
baseurl_posts_img:   '/assets/images/posts/'
baseurl_featured_img: '/assets/images/hero/'
baseurl_featured_thumbnail: '/assets/images/thumbnail/'
baseurl_javascripts: '/assets/javascripts/'
icon:                your site icon path # /assets/img/icon.png [best 300px X 300px]
disqus:              fabiopereirame # get it on https://disqus.com/admin/

author:
  name:           	 Fabio Pereira
  url:            	 http://www.fabiopereira.me
  facebook:          fabiopereira.me
  twitter:           fabiopereira
  google_plus:       username
  linkedin:          fabiopereirame
  dribbble:          username
  pinterest:         username
  kiva:              username

fb_admins:           your facebook profile id
fb_appid:            your facebook app id

# Server
destination:      	 ./_site
exclude:          	 [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml"]
port:             	 9001

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
